# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=b'profile/default.png', max_length=500, upload_to=b'profile'),
        ),
    ]
