# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0012_post_show_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='grumblr/static/grumblr                            /images/profile/default.png', max_length=500, upload_to='grumblr/static/grumblr/images/profile'),
        ),
    ]
