# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0005_auto_20171007_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='grumblr/static/grumblr/images/default.png', max_length=500, upload_to='grumblr/static/grumblr/images/profile'),
        ),
    ]
