# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0008_auto_20171008_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='comfirmed',
            new_name='confirmed',
        ),
    ]
