# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0009_auto_20171008_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followed', to='grumblr.Profile'),
        ),
    ]
