# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0010_profile_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('content', models.CharField(max_length=420)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='grumblr.Post')),
                ('profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='grumblr.Profile')),
            ],
        ),
    ]
